export declare const FooterContainer: string
export declare const rectangleTopDiv: string
export declare const rectangleDownDiv: string
export declare const rectangleTop: string
export declare const rectangleDown: string
export declare const rectangleTopLogo: string
export declare const rectangleDownCopyright: string
export declare const FooterMain: string
export declare const FooterContent: string
export declare const FooterContentColumn: string
export declare const FooterContentColumnTitle: string
export declare const FooterContentColumnName: string
export declare const PFooterNameDiv: string
export declare const PFooterName: string
