export declare const Hero: string
export declare const HeroContainer: string
export declare const HeroContent: string
export declare const TextContent: string
export declare const Img: string
export declare const Hero1Img: string
export declare const ImgContent: string
export declare const TextContent1: string
export declare const Img1: string
export declare const Img2: string
export declare const HeroBackImgWithTile: string
export declare const TextContent4: string
export declare const TextContent5: string
export declare const HeroImgOnBottom: string
export declare const HeroBackImgWithText: string
export declare const TextContent3: string
export declare const ImgContent3: string
export declare const Img3: string
export declare const Img4: string
export declare const HeroHeader: string
export declare const HeroParagraph: string
