export declare const Popup: string
export declare const Header: string
export declare const Text: string
export declare const Point: string
export declare const Line0: string
export declare const Line: string
export declare const Title: string
export declare const Roadmap: string
export declare const Road: string
export declare const Background: string
