/// <reference types="react" />
export declare const SmallPointGradient: () => JSX.Element
export declare const SmallPointGradientBottom: () => JSX.Element
export declare const SmallPointGradientTop: () => JSX.Element
export declare const BigPointGradient: () => JSX.Element
export declare const BigPointGradientTop: () => JSX.Element
export declare const BigPointGradientBottom: () => JSX.Element
export declare const SmallPointBlue: () => JSX.Element
export declare const SmallPointBlueBottom: () => JSX.Element
export declare const SmallPointBlueTop: () => JSX.Element
export declare const BigPointBlue: () => JSX.Element
export declare const BigPointBlueTop: () => JSX.Element
export declare const BigPointBlueBottom: () => JSX.Element
export declare const SmallPointInactive: () => JSX.Element
export declare const SmallPointInactiveBottom: () => JSX.Element
export declare const SmallPointInactiveTop: () => JSX.Element
export declare const SmallPointInactiveWhite: () => JSX.Element
export declare const SmallPointInactiveWhiteBottom: () => JSX.Element
export declare const SmallPointInactiveWhiteTop: () => JSX.Element
export declare const ActiveLineGradient0: () => JSX.Element
export declare const ActiveLineGradient1: () => JSX.Element
export declare const ActiveLineGradient2: () => JSX.Element
export declare const ActiveLineGradient3: () => JSX.Element
export declare const ActiveLineGradient4: () => JSX.Element
export declare const ActiveLineGradient5: () => JSX.Element
export declare const ActiveLineGradient6: () => JSX.Element
export declare const ActiveLineGradient7: () => JSX.Element
export declare const ActiveLineBlue0: () => JSX.Element
export declare const ActiveLineBlue1: () => JSX.Element
export declare const ActiveLineBlue2: () => JSX.Element
export declare const ActiveLineBlue3: () => JSX.Element
export declare const ActiveLineBlue4: () => JSX.Element
export declare const ActiveLineBlue5: () => JSX.Element
export declare const ActiveLineBlue6: () => JSX.Element
export declare const ActiveLineBlue7: () => JSX.Element
export declare const InactiveLine0: () => JSX.Element
export declare const InactiveLine1: () => JSX.Element
export declare const InactiveLine2: () => JSX.Element
export declare const InactiveLine3: () => JSX.Element
export declare const InactiveLine4: () => JSX.Element
export declare const InactiveLine5: () => JSX.Element
export declare const InactiveLine6: () => JSX.Element
export declare const InactiveLine7: () => JSX.Element
export declare const BackgroundLine0: () => JSX.Element
export declare const BackgroundLine1: () => JSX.Element
export declare const BackgroundLine2: () => JSX.Element
export declare const BackgroundLine3: () => JSX.Element
export declare const BackgroundLine4: () => JSX.Element
export declare const BackgroundLine5: () => JSX.Element
export declare const BackgroundLine6: () => JSX.Element
export declare const BackgroundLine7: () => JSX.Element
export declare const BackgroundLineBlue0: () => JSX.Element
export declare const BackgroundLineBlue1: () => JSX.Element
export declare const BackgroundLineBlue2: () => JSX.Element
export declare const BackgroundLineBlue3: () => JSX.Element
export declare const BackgroundLineBlue4: () => JSX.Element
export declare const BackgroundLineBlue5: () => JSX.Element
export declare const BackgroundLineBlue6: () => JSX.Element
export declare const BackgroundLineBlue7: () => JSX.Element
export declare const loadActiveLineBlue: (idx: number) => JSX.Element
export declare const loadActiveLineGradient: (idx: number) => JSX.Element
export declare const loadInactiveLine: (idx: number) => JSX.Element
export declare const loadBackgroundLine: (idx: number) => JSX.Element
export declare const loadBackgroundLineBlue: (idx: number) => JSX.Element
